// <auto-generated />
using ApiCampTajamar.Model;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage;
using Microsoft.EntityFrameworkCore.Storage.Internal;
using System;

namespace ApiCampTajamar.Migrations
{
    [DbContext(typeof(ProductoContext))]
    [Migration("20180317111818_usuarios")]
    partial class usuarios
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.0.2-rtm-10011")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("ApiCampTajamar.Model.Categoria", b =>
                {
                    b.Property<int>("IdCategoria")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Nombre");

                    b.HasKey("IdCategoria");

                    b.ToTable("Categoria");
                });

            modelBuilder.Entity("ApiCampTajamar.Model.Producto", b =>
                {
                    b.Property<int>("IdProducto")
                        .ValueGeneratedOnAdd();

                    b.Property<int?>("CategoriaIdCategoria");

                    b.Property<int>("Existencias");

                    b.Property<string>("Nombre");

                    b.Property<double>("Precio");

                    b.HasKey("IdProducto");

                    b.HasIndex("CategoriaIdCategoria");

                    b.ToTable("Producto");
                });

            modelBuilder.Entity("ApiCampTajamar.Model.ProductoTienda", b =>
                {
                    b.Property<int>("IdProducto");

                    b.Property<int>("IdTienda");

                    b.HasKey("IdProducto", "IdTienda");

                    b.HasIndex("IdTienda");

                    b.ToTable("ProductoTienda");
                });

            modelBuilder.Entity("ApiCampTajamar.Model.Tienda", b =>
                {
                    b.Property<int>("IdTienda")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Nombre");

                    b.HasKey("IdTienda");

                    b.ToTable("Tienda");
                });

            modelBuilder.Entity("ApiCampTajamar.Model.Usuario", b =>
                {
                    b.Property<int>("IdUsuario")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Login");

                    b.Property<string>("Password");

                    b.HasKey("IdUsuario");

                    b.ToTable("Usuario");
                });

            modelBuilder.Entity("ApiCampTajamar.Model.Producto", b =>
                {
                    b.HasOne("ApiCampTajamar.Model.Categoria", "Categoria")
                        .WithMany("Producto")
                        .HasForeignKey("CategoriaIdCategoria");
                });

            modelBuilder.Entity("ApiCampTajamar.Model.ProductoTienda", b =>
                {
                    b.HasOne("ApiCampTajamar.Model.Producto", "Producto")
                        .WithMany("ProductoTienda")
                        .HasForeignKey("IdProducto")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("ApiCampTajamar.Model.Tienda", "Tienda")
                        .WithMany("ProductoTienda")
                        .HasForeignKey("IdTienda")
                        .OnDelete(DeleteBehavior.Cascade);
                });
#pragma warning restore 612, 618
        }
    }
}
